MvcSample2/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcSample2.Controllers
{
    public class StoreController : Controller
    {
        // GET: Store
        public ActionResult Index()
        {
            ViewBag.Titty = "Store Front";
            return View();
        }



        // GET: /Store/
        //public string Index()
        //{
        //    return "Hello from Store.Index()";
        //}
        public ActionResult Browse()
        {
            ViewBag.Title = "Store -> Catalog";
            return View();
        }


        // GET: /Store/Browse?genre=drama
        public string Browse(string genre)
        {
            return //"Hello from Store.Browse()";
                    HttpUtility.HtmlEncode("Browse > Genre > " + genre);
        }
        //
        // GET: /Store/Details/5
        public string Details(int id)
        {
            //return "Hello from Store.Details()";
            string message = "Store.Details, ID = " + id;
            return message;
        }
    }
}

MvcSample2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Music App.</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
         
                </button>
               
                @Html.ActionLink("MVC Music", "Index", "Store",null, new { @class = "navbar-brand" })
             </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
 
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Music Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>